# arguments for dataset
dataset: cityscapes
nclass: 19
crop_size: 769
data_root: ../semi-supervised-segmentation/data/cityscapes/

# arguments for training
epochs: 240
batch_size: 1
lr: 0.005  # 8GPUs
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 100000

## confidence threshold for fixmatch
conf_thresh: 0.95
## data percentage threshold for DPA with s4mc
data_percentage: 0.75
neighbourhood_size: 4
neighbours: 1

# arguments for model
backbone: resnet101
multi_grid: True
replace_stride_with_dilation: [False, True, True]
dilations: [12, 24, 36]
